version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

jobs:
  build:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: cd viewer && npm install && npm run build
      - persist_to_workspace:
          root: viewer
          paths: dist

  deploy-html:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - gh-pages/deploy:
          build-dir: dist/
          ssh-fingerprints: "09:d7:09:7e:47:5e:0d:2c:a1:4b:1a:3a:1c:c0:e9:b1"

workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            ignore:
              - gh-pages
      - deploy-html:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
