version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: cd viewer && npm install && npm run build
      - persist_to_workspace:
          root: viewer
          paths: dist

  deploy-html:
    docker:
      - image: node:current-alpine
    steps:
      - attach_workspace:
          at: dist
      - add_ssh_keys:
          fingerprints:
            - "ef:d4:88:5b:db:73:3f:c9:cc:31:fb:53:57:f4:8a:83"
      - run:
          command: |
          npm install -g --silent gh-pages
          git config user.email "build@apertus.org"
          git config user.name "${CIRCLE_USERNAME}"
      - run:
        name: Deploy docs to gh-pages branch
        command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-html
