version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: cd viewer && npm install && npm run build
      - persist_to_workspace:
          root: viewer
          paths: dist

  deploy-html:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - add_ssh_keys:
          fingerprints:
            - "09:d7:09:7e:47:5e:0d:2c:a1:4b:1a:3a:1c:c0:e9:b1"
      - run:
          command: |
            git config user.email "build@apertus.org"
            git config user.name "ci-build"
            git push origin `git subtree split --prefix dist main`:gh-pages --force -v

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-html:
          requires:
            - build
          filters:
            branches:
              only: main
