version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: cd viewer && npm install && npm run build
      - persist_to_workspace:
          root: viewer
          paths: dist

  deploy-html:
    docker:
      - image: node:current-alpine
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - add_ssh_keys:
          fingerprints:
            - "ef:d4:88:5b:db:73:3f:c9:cc:31:fb:53:57:f4:8a:83"
      - run:
          command: |
            apk add --no-cache git git-subtree openssh
            git config user.email "build@apertus.org"
            git config user.name "ci-build"
            git push origin `git subtree split --prefix dist master`:gh-pages --force -v

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-html:
          requires:
            - build
          filters:
            branches:
              only: main
